import { Inter } from "next/font/google";
import "./globals.css";

import Header from "@/components/header";
import NavMenu from "@/components/navMenu";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <NavMenu />
          {children}
        <Footer />
      </body>
    </html>
  );
}
