import { Inter } from "next/font/google";
import "./globals.css";
import StandardLayout from "@/components/standardLayout";
import AlternativeLayout from "@/components/alternativeLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {true ? (
          <StandardLayout />
        ) : (
          <AlternativeLayout />
        )}
        {children}
      </body>
    </html>
  );
}
